// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p := messageKeyToIndex[key]
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"sl": &dictionary{index: slIndex, data: slData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%.2f\u00a0GiB":                         21,
	"%.2f\u00a0KiB":                         19,
	"%.2f\u00a0MiB":                         20,
	"%.2f\u00a0TiB":                         22,
	"%d day(s)":                             13,
	"%d hour(s)":                            14,
	"%d minute(s)":                          15,
	"%d second(s)":                          16,
	"%d tunnels were unable to be removed.": 161,
	"%d year(s)":                            12,
	"%d\u00a0B":                             18,
	"%s\n\nPlease consult the log for more information.": 114,
	"%s (out of date)":                        115,
	"%s (unsigned build, no updates)":         166,
	"%s You cannot undo this action.":         157,
	"%s ago":                                  17,
	"%s received, %s sent":                    74,
	"%s: %q":                                  23,
	"&About WireGuard…":                       112,
	"&Activate":                               60,
	"&Block untunneled traffic (kill-switch)": 85,
	"&Configuration:":                         89,
	"&Copy":                                   105,
	"&Deactivate":                             59,
	"&Edit":                                   136,
	"&Import tunnel(s) from file…":            122,
	"&Manage tunnels…":                        121,
	"&Name:":                                  82,
	"&Public key:":                            83,
	"&Remove selected tunnel(s)":              144,
	"&Save":                                   87,
	"&Save to file…":                          107,
	"&Toggle":                                 141,
	"(no argument): elevate and install manager service": 1,
	"(unknown)":                             84,
	"A name is required.":                   91,
	"A tunnel was unable to be removed: %s": 159,
	"About WireGuard":                       53,
	"Activating":                            100,
	"Active":                                99,
	"Add &empty tunnel…":                    137,
	"Add Tunnel":                            138,
	"Addresses:":                            64,
	"Addresses: %s":                         127,
	"Addresses: None":                       120,
	"All peers must have public keys":       47,
	"Allowed IPs:":                          68,
	"An Update is Available!":               132,
	"An interface must have a private key":  45,
	"An update to WireGuard is available. It is highly advisable to update without delay.":            169,
	"An update to WireGuard is now available. You are advised to update as soon as possible.":         134,
	"Another tunnel already exists with the name ‘%s’":                                                147,
	"Another tunnel already exists with the name ‘%s’.":                                               95,
	"App version: %s\nGo backend version: %s\nGo version: %s\nOperating system: %s\nArchitecture: %s": 55,
	"Are you sure you would like to delete %d tunnels?":                                               154,
	"Are you sure you would like to delete tunnel ‘%s’?":                                              156,
	"Brackets must contain an IPv6 address":                                                           28,
	"Cancel":                                                                                          88,
	"Close":                                                                                           56,
	"Command Line Options":                                                                            3,
	"Configuration Files (*.zip, *.conf)|*.zip;*.conf|All Files (*.*)|*.*":                            162,
	"Configuration ZIP Files (*.zip)|*.zip":                                                           164,
	"Could not enumerate existing tunnels: %v":                                                        146,
	"Could not import selected configuration: %v":                                                     145,
	"Create new tunnel":                                                                               80,
	"DNS servers:":                                                                                    65,
	"DNS suffix:":                                                                                     66,
	"Deactivating":                                                                                    102,
	"Delete %d tunnels":                                                                               153,
	"Delete tunnel ‘%s’":                                                                              155,
	"E&xit":                                                                                           123,
	"Edit &selected tunnel…":                                                                          143,
	"Edit tunnel":                                                                                     81,
	"Endpoint:":                                                                                       69,
	"Error":                                                                                           0,
	"Error Exiting WireGuard":                                                                         167,
	"Error in getting configuration":                                                                  48,
	"Error: %v. Please try again.":                                                                    173,
	"Export all tunnels to &zip…":                                                                     142,
	"Export all tunnels to zip":                                                                       140,
	"Export log to file":                                                                              111,
	"Export tunnels to zip":                                                                           165,
	"Failed to activate tunnel":                                                                       76,
	"Failed to deactivate tunnel":                                                                     77,
	"Failed to determine tunnel state":                                                                75,
	"File ‘%s’ already exists.\n\nDo you want to overwrite it?":                                       98,
	"Hostname must not be empty":                                                                      35,
	"Hostname must not exceed 255 characters":                                                         36,
	"Import tunnel(s) from file":                                                                      163,
	"Imported %d of %d tunnels":                                                                       151,
	"Imported %d tunnels":                                                                             150,
	"Imported tunnels":                                                                                149,
	"Inactive":                                                                                        101,
	"Interface: %s":                                                                                   78,
	"Invalid IP address":                                                                              24,
	"Invalid MTU":                                                                                     29,
	"Invalid config key is missing an equals separator":                                               41,
	"Invalid domain name":                                                                             37,
	"Invalid endpoint host":                                                                           27,
	"Invalid key for [Interface] section":                                                             43,
	"Invalid key for [Peer] section":                                                                  44,
	"Invalid key for interface section":                                                               49,
	"Invalid key for peer section":                                                                    51,
	"Invalid key: %v":                                                                                 32,
	"Invalid name":                                                                                    90,
	"Invalid network prefix length":                                                                   25,
	"Invalid persistent keepalive":                                                                    31,
	"Invalid port":                                                                                    30,
	"Key must have a value":                                                                           42,
	"Keys must decode to exactly 32 bytes":                                                            33,
	"Latest handshake:":                                                                               71,
	"Line must occur in a section":                                                                    40,
	"Listen port:":                                                                                    62,
	"Log":                                                                                             104,
	"Log message":                                                                                     109,
	"MTU:":                                                                                            63,
	"Missing port from endpoint":                                                                      26,
	"Now":                                                                                             10,
	"Number must be a number between 0 and 2^64-1: %v":                                                34,
	"Peer":                                79,
	"Persistent keepalive:":               70,
	"Preshared key:":                      67,
	"Protocol version must be 1":          50,
	"Public key:":                         61,
	"Remove selected tunnel(s)":           139,
	"Select &all":                         106,
	"Status:":                             58,
	"Status: %s":                          126,
	"Status: Complete!":                   174,
	"Status: Unknown":                     119,
	"Status: Waiting for updater service": 172,
	"Status: Waiting for user":            170,
	"System clock wound backward!":        11,
	"Text Files (*.txt)|*.txt|All Files (*.*)|*.*": 110,
	"The %s tunnel has been activated.":            129,
	"The %s tunnel has been deactivated.":          131,
	"Time":                                         108,
	"Transfer:":                                    72,
	"Tunnel Error":                                 113,
	"Tunnel already exists":                        94,
	"Tunnel name is not valid":                     39,
	"Tunnel name ‘%s’ is invalid.":                 92,
	"Tunnels":                                      135,
	"Two commas in a row":                          38,
	"Unable to create new configuration":           96,
	"Unable to create tunnel":                      152,
	"Unable to delete tunnel":                      158,
	"Unable to delete tunnels":                     160,
	"Unable to determine whether the process is running under WOW64: %v":                          4,
	"Unable to exit service due to: %v. You may want to stop WireGuard from the service manager.": 168,
	"Unable to import configuration: %v":                                                          148,
	"Unable to list existing tunnels":                                                             93,
	"Unable to open current process token: %v":                                                    6,
	"Unable to wait for WireGuard window to appear: %v":                                           117,
	"Unknown state":    103,
	"Update Now":       171,
	"Usage: %s [\n%s]": 2,
	"When a configuration has exactly one peer, and that peer has an allowed IPs containing at least one of 0.0.0.0/0 or ::/0, then the tunnel service engages a firewall ruleset to block all traffic that is neither to nor from the tunnel interface, with special exceptions for DHCP and NDP.": 86,
	"WireGuard Activated":        128,
	"WireGuard Deactivated":      130,
	"WireGuard Detection Error":  116,
	"WireGuard Tunnel Error":     124,
	"WireGuard Update Available": 133,
	"WireGuard is running, but the UI is only accessible from desktops of the Builtin %s group.": 8,
	"WireGuard logo image": 54,
	"WireGuard may only be used by users who are a member of the Builtin %s group.": 7,
	"WireGuard system tray icon did not appear after 30 seconds.":                   9,
	"WireGuard: %s":          125,
	"WireGuard: Deactivated": 118,
	"Writing file failed":    97,
	"You must use the 64-bit version of WireGuard on this computer.": 5,
	"[EnumerationSeparator]": 52,
	"[none specified]":       46,
	"enabled":                73,
	"http2: Framer %p: failed to decode just-written frame": 175,
	"http2: Framer %p: read %v":                             177,
	"http2: Framer %p: wrote %v":                            176,
	"http2: decoded hpack field %+v":                        178,
	"♥ &Donate!":                                            57,
}

var enIndex = []uint32{ // 180 elements
	// Entry 0 - 1F
	0x00000000, 0x00000006, 0x00000039, 0x0000004f,
	0x00000064, 0x000000aa, 0x000000e9, 0x00000115,
	0x00000166, 0x000001c4, 0x00000200, 0x00000204,
	0x00000221, 0x00000241, 0x0000025f, 0x0000027f,
	0x000002a3, 0x000002c7, 0x000002d1, 0x000002da,
	0x000002e7, 0x000002f4, 0x00000301, 0x0000030e,
	0x0000031b, 0x0000032e, 0x0000034c, 0x00000367,
	0x0000037d, 0x000003a3, 0x000003af, 0x000003bc,
	// Entry 20 - 3F
	0x000003d9, 0x000003ec, 0x00000411, 0x00000445,
	0x00000460, 0x00000488, 0x0000049c, 0x000004b0,
	0x000004c9, 0x000004e6, 0x00000518, 0x0000052e,
	0x00000552, 0x00000571, 0x00000596, 0x000005a7,
	0x000005c7, 0x000005e6, 0x00000608, 0x00000623,
	0x00000640, 0x00000643, 0x00000653, 0x00000668,
	0x000006d3, 0x000006d9, 0x000006e6, 0x000006ee,
	0x000006fa, 0x00000704, 0x00000710, 0x0000071d,
	// Entry 40 - 5F
	0x00000722, 0x0000072d, 0x0000073a, 0x00000746,
	0x00000755, 0x00000762, 0x0000076c, 0x00000782,
	0x00000794, 0x0000079e, 0x000007a6, 0x000007c1,
	0x000007e2, 0x000007fc, 0x00000818, 0x00000829,
	0x0000082e, 0x00000840, 0x0000084c, 0x00000853,
	0x00000860, 0x0000086a, 0x00000892, 0x000009b0,
	0x000009b6, 0x000009bd, 0x000009cd, 0x000009da,
	0x000009ee, 0x00000a12, 0x00000a32, 0x00000a48,
	// Entry 60 - 7F
	0x00000a81, 0x00000aa4, 0x00000ab8, 0x00000af7,
	0x00000afe, 0x00000b09, 0x00000b12, 0x00000b1f,
	0x00000b2d, 0x00000b31, 0x00000b37, 0x00000b43,
	0x00000b54, 0x00000b59, 0x00000b65, 0x00000b92,
	0x00000ba5, 0x00000bb9, 0x00000bc6, 0x00000bfa,
	0x00000c0e, 0x00000c28, 0x00000c5d, 0x00000c74,
	0x00000c84, 0x00000c94, 0x00000ca7, 0x00000cc6,
	0x00000ccc, 0x00000ce3, 0x00000cf4, 0x00000d02,
	// Entry 80 - 9F
	0x00000d13, 0x00000d27, 0x00000d4c, 0x00000d62,
	0x00000d89, 0x00000da1, 0x00000dbc, 0x00000e14,
	0x00000e1c, 0x00000e22, 0x00000e37, 0x00000e42,
	0x00000e5c, 0x00000e76, 0x00000e7e, 0x00000e9c,
	0x00000eb5, 0x00000ed0, 0x00000eff, 0x00000f2b,
	0x00000f63, 0x00000f89, 0x00000f9a, 0x00000fd0,
	0x00001017, 0x0000102f, 0x00001061, 0x000010d3,
	0x000010ed, 0x00001127, 0x0000114a, 0x00001162,
	// Entry A0 - BF
	0x0000118b, 0x000011a4, 0x000011fd, 0x00001242,
	0x0000125d, 0x00001283, 0x00001299, 0x000012bc,
	0x000012d4, 0x00001333, 0x00001388, 0x000013a1,
	0x000013ac, 0x000013d0, 0x000013f0, 0x00001402,
	0x0000143b, 0x0000145c, 0x0000147c, 0x0000149e,
} // Size: 744 bytes

const enData string = "" + // Size: 5278 bytes
	"\x02Error\x02(no argument): elevate and install manager service\x02Usage" +
	": %[1]s [\x0a%[2]s]\x02Command Line Options\x02Unable to determine wheth" +
	"er the process is running under WOW64: %[1]v\x02You must use the 64-bit " +
	"version of WireGuard on this computer.\x02Unable to open current process" +
	" token: %[1]v\x02WireGuard may only be used by users who are a member of" +
	" the Builtin %[1]s group.\x02WireGuard is running, but the UI is only ac" +
	"cessible from desktops of the Builtin %[1]s group.\x02WireGuard system t" +
	"ray icon did not appear after 30 seconds.\x02Now\x02System clock wound b" +
	"ackward!\x14\x01\x81\x01\x00\x02\x0b\x02%[1]d year\x00\x0c\x02%[1]d year" +
	"s\x14\x01\x81\x01\x00\x02\x0a\x02%[1]d day\x00\x0b\x02%[1]d days\x14\x01" +
	"\x81\x01\x00\x02\x0b\x02%[1]d hour\x00\x0c\x02%[1]d hours\x14\x01\x81" +
	"\x01\x00\x02\x0d\x02%[1]d minute\x00\x0e\x02%[1]d minutes\x14\x01\x81" +
	"\x01\x00\x02\x0d\x02%[1]d second\x00\x0e\x02%[1]d seconds\x02%[1]s ago" +
	"\x02%[1]d\u00a0B\x02%.2[1]f\u00a0KiB\x02%.2[1]f\u00a0MiB\x02%.2[1]f" +
	"\u00a0GiB\x02%.2[1]f\u00a0TiB\x02%[1]s: %[2]q\x02Invalid IP address\x02I" +
	"nvalid network prefix length\x02Missing port from endpoint\x02Invalid en" +
	"dpoint host\x02Brackets must contain an IPv6 address\x02Invalid MTU\x02I" +
	"nvalid port\x02Invalid persistent keepalive\x02Invalid key: %[1]v\x02Key" +
	"s must decode to exactly 32 bytes\x02Number must be a number between 0 a" +
	"nd 2^64-1: %[1]v\x02Hostname must not be empty\x02Hostname must not exce" +
	"ed 255 characters\x02Invalid domain name\x02Two commas in a row\x02Tunne" +
	"l name is not valid\x02Line must occur in a section\x02Invalid config ke" +
	"y is missing an equals separator\x02Key must have a value\x02Invalid key" +
	" for [Interface] section\x02Invalid key for [Peer] section\x02An interfa" +
	"ce must have a private key\x02[none specified]\x02All peers must have pu" +
	"blic keys\x02Error in getting configuration\x02Invalid key for interface" +
	" section\x02Protocol version must be 1\x02Invalid key for peer section" +
	"\x02, \x02About WireGuard\x02WireGuard logo image\x02App version: %[1]s" +
	"\x0aGo backend version: %[2]s\x0aGo version: %[3]s\x0aOperating system: " +
	"%[4]s\x0aArchitecture: %[5]s\x02Close\x02♥ &Donate!\x02Status:\x02&Deact" +
	"ivate\x02&Activate\x02Public key:\x02Listen port:\x02MTU:\x02Addresses:" +
	"\x02DNS servers:\x02DNS suffix:\x02Preshared key:\x02Allowed IPs:\x02End" +
	"point:\x02Persistent keepalive:\x02Latest handshake:\x02Transfer:\x02ena" +
	"bled\x02%[1]s received, %[2]s sent\x02Failed to determine tunnel state" +
	"\x02Failed to activate tunnel\x02Failed to deactivate tunnel\x02Interfac" +
	"e: %[1]s\x02Peer\x02Create new tunnel\x02Edit tunnel\x02&Name:\x02&Publi" +
	"c key:\x02(unknown)\x02&Block untunneled traffic (kill-switch)\x02When a" +
	" configuration has exactly one peer, and that peer has an allowed IPs co" +
	"ntaining at least one of 0.0.0.0/0 or ::/0, then the tunnel service enga" +
	"ges a firewall ruleset to block all traffic that is neither to nor from " +
	"the tunnel interface, with special exceptions for DHCP and NDP.\x02&Save" +
	"\x02Cancel\x02&Configuration:\x02Invalid name\x02A name is required.\x02" +
	"Tunnel name ‘%[1]s’ is invalid.\x02Unable to list existing tunnels\x02Tu" +
	"nnel already exists\x02Another tunnel already exists with the name ‘%[1]" +
	"s’.\x02Unable to create new configuration\x02Writing file failed\x02File" +
	" ‘%[1]s’ already exists.\x0a\x0aDo you want to overwrite it?\x02Active" +
	"\x02Activating\x02Inactive\x02Deactivating\x02Unknown state\x02Log\x02&C" +
	"opy\x02Select &all\x02&Save to file…\x02Time\x02Log message\x02Text File" +
	"s (*.txt)|*.txt|All Files (*.*)|*.*\x02Export log to file\x02&About Wire" +
	"Guard…\x02Tunnel Error\x02%[1]s\x0a\x0aPlease consult the log for more i" +
	"nformation.\x02%[1]s (out of date)\x02WireGuard Detection Error\x02Unabl" +
	"e to wait for WireGuard window to appear: %[1]v\x02WireGuard: Deactivate" +
	"d\x02Status: Unknown\x02Addresses: None\x02&Manage tunnels…\x02&Import t" +
	"unnel(s) from file…\x02E&xit\x02WireGuard Tunnel Error\x02WireGuard: %[1" +
	"]s\x02Status: %[1]s\x02Addresses: %[1]s\x02WireGuard Activated\x02The %[" +
	"1]s tunnel has been activated.\x02WireGuard Deactivated\x02The %[1]s tun" +
	"nel has been deactivated.\x02An Update is Available!\x02WireGuard Update" +
	" Available\x02An update to WireGuard is now available. You are advised t" +
	"o update as soon as possible.\x02Tunnels\x02&Edit\x02Add &empty tunnel…" +
	"\x02Add Tunnel\x02Remove selected tunnel(s)\x02Export all tunnels to zip" +
	"\x02&Toggle\x02Export all tunnels to &zip…\x02Edit &selected tunnel…\x02" +
	"&Remove selected tunnel(s)\x02Could not import selected configuration: %" +
	"[1]v\x02Could not enumerate existing tunnels: %[1]v\x02Another tunnel al" +
	"ready exists with the name ‘%[1]s’\x02Unable to import configuration: %[" +
	"1]v\x02Imported tunnels\x14\x01\x81\x01\x00\x02\x16\x02Imported %[1]d tu" +
	"nnel\x00\x17\x02Imported %[1]d tunnels\x14\x02\x80\x01\x02\x1f\x02Import" +
	"ed %[1]d of %[2]d tunnel\x00 \x02Imported %[1]d of %[2]d tunnels\x02Unab" +
	"le to create tunnel\x14\x01\x81\x01\x00\x02\x14\x02Delete %[1]d tunnel" +
	"\x00\x15\x02Delete %[1]d tunnels\x14\x01\x81\x01\x00\x024\x02Are you sur" +
	"e you would like to delete %[1]d tunnel?\x005\x02Are you sure you would " +
	"like to delete %[1]d tunnels?\x02Delete tunnel ‘%[1]s’\x02Are you sure y" +
	"ou would like to delete tunnel ‘%[1]s’?\x02%[1]s You cannot undo this ac" +
	"tion.\x02Unable to delete tunnel\x02A tunnel was unable to be removed: %" +
	"[1]s\x02Unable to delete tunnels\x14\x01\x81\x01\x00\x02'\x02%[1]d tunne" +
	"l was unable to be removed.\x00)\x02%[1]d tunnels were unable to be remo" +
	"ved.\x02Configuration Files (*.zip, *.conf)|*.zip;*.conf|All Files (*.*)" +
	"|*.*\x02Import tunnel(s) from file\x02Configuration ZIP Files (*.zip)|*." +
	"zip\x02Export tunnels to zip\x02%[1]s (unsigned build, no updates)\x02Er" +
	"ror Exiting WireGuard\x02Unable to exit service due to: %[1]v. You may w" +
	"ant to stop WireGuard from the service manager.\x02An update to WireGuar" +
	"d is available. It is highly advisable to update without delay.\x02Statu" +
	"s: Waiting for user\x02Update Now\x02Status: Waiting for updater service" +
	"\x02Error: %[1]v. Please try again.\x02Status: Complete!\x02http2: Frame" +
	"r %[1]p: failed to decode just-written frame\x02http2: Framer %[1]p: wro" +
	"te %[2]v\x02http2: Framer %[1]p: read %[2]v\x02http2: decoded hpack fiel" +
	"d %+[1]v"

var slIndex = []uint32{ // 180 elements
	// Entry 0 - 1F
	0x00000000, 0x00000007, 0x00000058, 0x00000070,
	0x00000089, 0x000000c1, 0x00000107, 0x0000013e,
	0x00000190, 0x000001f6, 0x0000023a, 0x0000023f,
	0x0000025e, 0x00000296, 0x000002cd, 0x00000301,
	0x00000341, 0x00000385, 0x00000391, 0x0000039a,
	0x000003a7, 0x000003b4, 0x000003c1, 0x000003ce,
	0x000003db, 0x000003ee, 0x00000412, 0x00000434,
	0x0000045d, 0x00000483, 0x00000490, 0x0000049f,
	// Entry 20 - 3F
	0x000004c3, 0x000004da, 0x0000050b, 0x0000053f,
	0x00000561, 0x00000592, 0x000005aa, 0x000005bf,
	0x000005d6, 0x000005f1, 0x00000629, 0x00000644,
	0x00000669, 0x00000689, 0x000006ab, 0x000006b9,
	0x000006e0, 0x00000700, 0x00000722, 0x00000740,
	0x00000762, 0x00000765, 0x00000772, 0x00000790,
	0x00000805, 0x0000080b, 0x00000819, 0x00000821,
	0x0000082e, 0x00000839, 0x00000847, 0x0000085a,
	// Entry 40 - 5F
	0x0000085f, 0x00000868, 0x00000878, 0x00000885,
	0x0000089b, 0x000008ac, 0x000008bc, 0x000008d8,
	0x000008ea, 0x000008f2, 0x000008fd, 0x0000091a,
	0x0000093e, 0x0000095c, 0x0000097c, 0x0000098b,
	0x00000993, 0x000009a5, 0x000009b1, 0x000009b7,
	0x000009c6, 0x000009d0, 0x000009fa, 0x00000b1b,
	0x00000b23, 0x00000b2d, 0x00000b3d, 0x00000b4a,
	0x00000b5a, 0x00000b7c, 0x00000bac, 0x00000bbe,
	// Entry 60 - 7F
	0x00000be9, 0x00000c10, 0x00000c2e, 0x00000c69,
	0x00000c71, 0x00000c7d, 0x00000c87, 0x00000c95,
	0x00000ca4, 0x00000cac, 0x00000cb5, 0x00000cc1,
	0x00000cd9, 0x00000cde, 0x00000cf4, 0x00000d2c,
	0x00000d46, 0x00000d59, 0x00000d67, 0x00000d96,
	0x00000dac, 0x00000dc9, 0x00000e04, 0x00000e1b,
	0x00000e2a, 0x00000e38, 0x00000e4f, 0x00000e6e,
	0x00000e75, 0x00000e8d, 0x00000e9e, 0x00000eac,
	// Entry 80 - 9F
	0x00000ebb, 0x00000ecf, 0x00000eed, 0x00000f03,
	0x00000f23, 0x00000f3c, 0x00000f5c, 0x00000fa1,
	0x00000fa8, 0x00000faf, 0x00000fc8, 0x00000fd4,
	0x00000fec, 0x00001004, 0x0000100e, 0x0000102c,
	0x00001045, 0x0000105e, 0x0000108c, 0x000010bf,
	0x000010e4, 0x0000110a, 0x0000111a, 0x0000117e,
	0x0000120a, 0x00001226, 0x0000128b, 0x00001378,
	0x00001393, 0x000013ce, 0x000013f9, 0x00001413,
	// Entry A0 - BF
	0x0000143b, 0x00001456, 0x0000150a, 0x00001557,
	0x00001570, 0x0000159b, 0x000015af, 0x000015de,
	0x000015fe, 0x0000166b, 0x000016be, 0x000016da,
	0x000016e8, 0x0000170f, 0x00001731, 0x00001743,
	0x0000178b, 0x000017af, 0x000017d3, 0x000017f8,
} // Size: 744 bytes

const slData string = "" + // Size: 6136 bytes
	"\x02Napaka\x02(brez argumenta): povzdigni na skrbniške pravice in namest" +
	"i skrbniško storitev\x02Uporaba: %[1]s [\x0a%[2]s]\x02Možnosti ukazne vr" +
	"stice\x02Napaka pri določanju ali proces teče kot WOW64: %[1]v\x02Na tem" +
	"u računalniku morate uporabiti 64-bitno različico WireGuarda.\x02Napaka " +
	"pri odpiranju žetona trenutnega procesa: %[1]v\x02WireGuard lahko uporab" +
	"ljajo samo uporabniki, ki so člani vgrajene skupine %[1]s.\x02WireGuard " +
	"je zagnan, vendar je up. vmesnik dostopen samo z namizij uporabnikov čla" +
	"nov skupine %[1]s.\x02Ikona WireGuarda se po 30 sekundah ni pojavila v s" +
	"istemski vrstici.\x02Zdaj\x02Sistemska ura prevrtena nazaj!\x14\x01\x81" +
	"\x01\x00\x04\x0b\x02%[1]d leta\x02\x0b\x02%[1]d leto\x03\x0b\x02%[1]d le" +
	"ti\x00\x0a\x02%[1]d let\x14\x01\x81\x01\x00\x04\x0a\x02%[1]d dni\x02\x0a" +
	"\x02%[1]d dan\x03\x0c\x02%[1]d dneva\x00\x0a\x02%[1]d dni\x14\x01\x81" +
	"\x01\x00\x04\x0a\x02%[1]d ure\x02\x0a\x02%[1]d uro\x03\x0a\x02%[1]d uri" +
	"\x00\x09\x02%[1]d ur\x14\x01\x81\x01\x00\x04\x0d\x02%[1]d minute\x02\x0d" +
	"\x02%[1]d minuto\x03\x0d\x02%[1]d minuti\x00\x0c\x02%[1]d minut\x14\x01" +
	"\x81\x01\x00\x04\x0e\x02%[1]d sekunde\x02\x0e\x02%[1]d sekundo\x03\x0e" +
	"\x02%[1]d sekundi\x00\x0d\x02%[1]d sekund\x02%[1]s nazaj\x02%[1]d\u00a0B" +
	"\x02%.2[1]f\u00a0KiB\x02%.2[1]f\u00a0MiB\x02%.2[1]f\u00a0GiB\x02%.2[1]f" +
	"\u00a0TiB\x02%[1]s: %[2]q\x02Napačen naslov IP\x02Napačna dolžina predpo" +
	"ne omrežja\x02Pri končni točki manjkajo vrata\x02Pri končni točki je gos" +
	"titelj napačen\x02Oklepaji morajo vsebovati naslov IPv6\x02Napačen MTU" +
	"\x02Napačna vrata\x02Napačno trajno ohranjanje povezave\x02Napačen ključ" +
	": %[1]v\x02Dekodirani ključi morajo biti natanko 32 bajtov\x02Številka m" +
	"ora biti število med 0 in 2^64-1: %[1]v\x02Ime gostitelja ne sme biti pr" +
	"azno\x02Ime gostitelja ne sme biti daljše od 255 znakov\x02Neveljavno do" +
	"mensko ime\x02Dve zaporedni vejici\x02Ime tunela ni veljavno\x02Vrstica " +
	"mora biti v odseku\x02Napačnemu ključu konfiguracije manjka ločilo-enača" +
	"j\x02Ključ mora imeti vrednost\x02Napačen ključ za odsek [Interface]\x02" +
	"Napačen ključ za odsek [Peer]\x02Vmesnik mora imeti zasebni ključ\x02[ni" +
	" navedeno]\x02Vsi vrstniki morajo imeti javni ključ\x02Napaka pri branju" +
	" konfiguracije\x02Napačen ključ za odsek vmesnika\x02Verzija protokola m" +
	"ora biti 1\x02Napačen ključ za odsek vrstnika\x02, \x02O WireGuardu\x02S" +
	"lika WireGuardovega logotipa\x02Verzija aplikacije: %[1]s\x0aVerzija wir" +
	"eguard-go: %[2]s\x0aVerzija Go: %[3]s\x0aOperacijski sistem: %[4]s\x0aAr" +
	"hitektura: %[5]s\x02Zapri\x02♥ &Doniraj!\x02Status:\x02&Deaktiviraj\x02&" +
	"Aktiviraj\x02Javni ključ:\x02Vrata poslušanja:\x02MTU:\x02Naslovi:\x02St" +
	"režniki DNS:\x02Pripona DNS:\x02Ključ v skupni rabi:\x02Dovoljeni IP-ji:" +
	"\x02Končna točka:\x02Trajno ohranjanje povezave:\x02Zadnje rokovanje:" +
	"\x02Prenos:\x02omogočeno\x02%[1]s prejeto, %[2]s poslano\x02Napaka pri d" +
	"oločanju stanja tunela\x02Napaka pri aktiviranju tunela\x02Napaka pri de" +
	"aktiviranju tunela\x02Vmesnik: %[1]s\x02Vrstnik\x02Ustvari nov tunel\x02" +
	"Uredi tunel\x02&Ime:\x02&Javni ključ:\x02(neznano)\x02&Blokiraj promet i" +
	"zven tunela (varovalka)\x02Kadar ima konfiguracija natanko enega vrstnik" +
	"a in njegov spisek dovoljenih IP-jev vsebuje vsaj enega izmed 0.0.0.0/0 " +
	"ali ::/0, bo storitev tunela vzpostavila pravila požarnega zidu, ki bodo" +
	" blokirala ves promet, ki ni niti za niti iz vmesnika tunela s posebnimi" +
	" izjemami za DHCP and NDP.\x02&Shrani\x02Prekliči\x02&Konfiguracija:\x02" +
	"Napačno ime\x02Ime je obvezno.\x02Ime tunela »%[1]s« ni veljavno.\x02Nap" +
	"aka pri pripravi seznama obstoječih tunelov\x02Tunel že obstaja\x02Drug " +
	"tunel z imenom »%[1]s« že obstaja.\x02Napaka pri izdelavi nove konfigura" +
	"cije\x02Napaka pri pisanju v datoteko\x02Datoteka »%[1]s« že obstaja." +
	"\x0a\x0aAli jo želite prepisati?\x02Aktiven\x02Se aktivira\x02Neaktiven" +
	"\x02Se deaktivira\x02Neznano stanje\x02Dnevnik\x02&Kopiraj\x02&Izberi vs" +
	"e\x02&Shrani v datoteko\u00a0…\x02Čas\x02Sporočilo v dnevniku\x02Tekstov" +
	"ne datoteke (*.txt)|*.txt|Vse datoteke (*.*)|*.*\x02Izvozi dnevnik v dat" +
	"oteko\x02O WireGu&ardu\u00a0…\x02Napaka tunela\x02%[1]s\x0a\x0aDodatne i" +
	"nformacije najdete v dnevniku.\x02%[1]s (neposodobljen)\x02Napaka zaznav" +
	"anja WireGuarda\x02Čakanje, da se pojavi WireGuardovo okno, ni možno: %[" +
	"1]v\x02WireGuard: Deaktiviran\x02Status: Neznan\x02Naslovi: Brez\x02&Upr" +
	"avljaj tunele\u00a0…\x02Uvoz&i tunele iz datoteke\u00a0…\x02I&zhod\x02Na" +
	"paka tunela WireGuard\x02WireGuard: %[1]s\x02Status: %[1]s\x02Naslovi: %" +
	"[1]s\x02WireGuard aktiviran\x02Tunel %[1]s je bil aktiviran.\x02WireGuar" +
	"d deaktiviran\x02Tunel %[1]s je bil deaktiviran.\x02Na voljo je posodobi" +
	"tev!\x02Posodobitev WireGuarda na voljo\x02Posodobitev WireGuarda je na " +
	"voljo. Svetujemo posodobitev čim prej.\x02Tuneli\x02Ur&edi\x02Dodaj praz" +
	"&en tunel\u00a0…\x02Dodaj tunel\x02Odstrani izbrane tunele\x02Izvozi vse" +
	" tunele v zip\x02&Preklopi\x02Izvozi vse tunele v &zip\u00a0…\x02Uredi i" +
	"&zbran tunel\u00a0…\x02Odst&rani izbrane tunele\x02Napaka pri uvozu izbr" +
	"ane konfiguracije: %[1]v\x02Napaka pri preštevanju obstoječih tunelov: %" +
	"[1]v\x02Tunel z imenom »%[1]s« že obstaja\x02Napaka pri uvozu konfigurac" +
	"ije: %[1]v\x02Uvoženi tuneli\x14\x01\x81\x01\x00\x04\x16\x02Uvoženi %[1]" +
	"d tuneli\x02\x14\x02Uvožen %[1]d tunel\x03\x16\x02Uvožena %[1]d tunela" +
	"\x00\x17\x02Uvoženo %[1]d tunelov\x14\x01\x81\x01\x00\x04 \x02Uvoženi %[" +
	"1]d od %[2]d tunelov\x02\x1f\x02Uvožen %[1]d od %[2]d tunelov\x03 \x02Uv" +
	"ožena %[1]d od %[2]d tunelov\x00 \x02Uvoženo %[1]d od %[2]d tunelov\x02N" +
	"apaka pri stvaritvi tunela\x14\x01\x81\x01\x00\x04\x16\x02Izbriši %[1]d " +
	"tunele\x02\x15\x02Izbriši %[1]d tunel\x03\x16\x02Izbriši %[1]d tunela" +
	"\x00\x17\x02Izbriši %[1]d tunelov\x14\x01\x81\x01\x00\x048\x02Ali ste pr" +
	"epričani, da želite izbrisati %[1]d tunele?\x027\x02Ali ste prepričani, " +
	"da želite izbrisati %[1]d tunel?\x038\x02Ali ste prepričani, da želite i" +
	"zbrisati %[1]d tunela?\x009\x02Ali ste prepričani, da želite izbrisati %" +
	"[1]d tunelov?\x02Izbriši tunel ‘%[1]s’\x02Ali ste prepričani, da želite " +
	"izbrisati tunel »%[1]s«?\x02%[1]s Tega dejanja ne morete razveljaviti." +
	"\x02Napaka pri izbrisu tunela\x02Napaka pri odstranjevanju tunela: %[1]s" +
	"\x02Napaka pri izbrisu tunelov\x14\x01\x81\x01\x00\x04*\x02%[1]d tunelov" +
	" ni bilo mogoče odstraniti.\x02)\x02%[1]d tunela ni bilo mogoče odstrani" +
	"ti.\x03*\x02%[1]d tunelov ni bilo mogoče odstraniti.\x00*\x02%[1]d tunel" +
	"ov ni bilo mogoče odstraniti.\x02Konfiguracijske datoteke (*.zip, *.conf" +
	")|*.zip;*.conf|Vse datoteke (*.*)|*.*\x02Uvozi tunele iz datoteke\x02Kon" +
	"figuracijske datoteke ZIP (*.zip)|*.zip\x02Izvozi tunele v zip\x02%[1]s " +
	"(nepodpisane izdelave, brez posodobitev)\x02Napaka pri izhodu iz WireGua" +
	"rda\x02Storitve ni bilo mogoče zaustaviti, ker: %[1]v. Poskusite zaustav" +
	"iti WireGuard z uporabo programa Storitve.\x02Posodobitev WireGuarda je " +
	"na voljo. Zelo priporočamo posodobitev brez odlašanja.\x02Status: Čaka n" +
	"a uporabnika\x02Posodobi zdaj\x02Status: Čaka na servis za posodobitev" +
	"\x02Napaka: %[1]v. Poskusite ponovno.\x02Status: Končano!\x02http2: Fram" +
	"er %[1]p: napaka pri dekodiranju ravnokar zapisanega okvirja\x02http2: F" +
	"ramer %[1]p: zapisano %[2]v\x02http2: Framer %[1]p: prebrano %[2]v\x02ht" +
	"tp2: dekodirano polje hpack %+[1]v"

	// Total table size 12902 bytes (12KiB); checksum: 635C370F
